// ------------
// enumerations
// ------------

#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<EnumerationPreferredEncoding>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<EnumerationCode>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<EnumerationLabelMode>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<EnumerationProtectMode>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<EnumerationMode>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<EnumerationLabelType>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<EnumerationKind>());
#endif

