// ------------
// structures
// ------------

#ifdef GLOBAL_NAMESPACE
auto ann_Reg32 = make_smart<Reg32_GeneratedAnnotation>(lib);
addAnnotation(ann_Reg32);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Ymm = make_smart<Ymm_GeneratedAnnotation>(lib);
addAnnotation(ann_Ymm);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Reg8 = make_smart<Reg8_GeneratedAnnotation>(lib);
addAnnotation(ann_Reg8);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Segment = make_smart<Segment_GeneratedAnnotation>(lib);
addAnnotation(ann_Segment);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_EvexModifierRounding = make_smart<EvexModifierRounding_GeneratedAnnotation>(lib);
addAnnotation(ann_EvexModifierRounding);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Operand = make_smart<Operand_GeneratedAnnotation>(lib);
addAnnotation(ann_Operand);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Fpu = make_smart<Fpu_GeneratedAnnotation>(lib);
addAnnotation(ann_Fpu);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_LabelManager = make_smart<LabelManager_GeneratedAnnotation>(lib);
addAnnotation(ann_LabelManager);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_CodeArray = make_smart<CodeArray_GeneratedAnnotation>(lib);
addAnnotation(ann_CodeArray);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Reg = make_smart<Reg_GeneratedAnnotation>(lib);
addAnnotation(ann_Reg);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Address = make_smart<Address_GeneratedAnnotation>(lib);
addAnnotation(ann_Address);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Label = make_smart<Label_GeneratedAnnotation>(lib);
addAnnotation(ann_Label);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_AddressFrame = make_smart<AddressFrame_GeneratedAnnotation>(lib);
addAnnotation(ann_AddressFrame);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_RegRip = make_smart<RegRip_GeneratedAnnotation>(lib);
addAnnotation(ann_RegRip);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Reg16 = make_smart<Reg16_GeneratedAnnotation>(lib);
addAnnotation(ann_Reg16);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Reg64 = make_smart<Reg64_GeneratedAnnotation>(lib);
addAnnotation(ann_Reg64);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Opmask = make_smart<Opmask_GeneratedAnnotation>(lib);
addAnnotation(ann_Opmask);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_RegExp = make_smart<RegExp_GeneratedAnnotation>(lib);
addAnnotation(ann_RegExp);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_EvexModifierZero = make_smart<EvexModifierZero_GeneratedAnnotation>(lib);
addAnnotation(ann_EvexModifierZero);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Allocator = make_smart<Allocator_GeneratedAnnotation>(lib);
addAnnotation(ann_Allocator);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Xmm = make_smart<Xmm_GeneratedAnnotation>(lib);
addAnnotation(ann_Xmm);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Reg32e = make_smart<Reg32e_GeneratedAnnotation>(lib);
addAnnotation(ann_Reg32e);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Zmm = make_smart<Zmm_GeneratedAnnotation>(lib);
addAnnotation(ann_Zmm);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_JmpLabel = make_smart<JmpLabel_GeneratedAnnotation>(lib);
addAnnotation(ann_JmpLabel);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Tmm = make_smart<Tmm_GeneratedAnnotation>(lib);
addAnnotation(ann_Tmm);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_BoundsReg = make_smart<BoundsReg_GeneratedAnnotation>(lib);
addAnnotation(ann_BoundsReg);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_CodeGenerator = make_smart<CodeGenerator_GeneratedAnnotation>(lib);
addAnnotation(ann_CodeGenerator);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_Mmx = make_smart<Mmx_GeneratedAnnotation>(lib);
addAnnotation(ann_Mmx);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Reg32,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Ymm,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Reg8,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Segment,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_EvexModifierRounding,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Operand,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Fpu,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_LabelManager,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_CodeArray,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Reg,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Address,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Label,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_AddressFrame,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_RegRip,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Reg16,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Reg64,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Opmask,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_RegExp,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_EvexModifierZero,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Allocator,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Xmm,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Reg32e,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Zmm,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_JmpLabel,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Tmm,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_BoundsReg,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_CodeGenerator,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_Mmx,lib);
#endif

